server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system # любое имя для задания
    static_configs:
      - targets:
          - "localhost" # список целей должен быть массивом строк
        labels:
          job: nextcloud_logs
          __path__: /opt/nc_data/*.log # путь к лог-файлам
